environment                  = "dev"
subscription_id              = "8486ac29-bcbd-4691-9ff6-52a901335eb0"
location                     = "francecentral"
resource_group_name          = "dev-nb-api-frc-rg"
identity_name                = "dev-nb-api-frc-id"
log_analytics_workspace_name = "dev-nb-api-frc-laws"
application_insights_name    = "dev-nb-api-frc-ai"
nsg_name                     = "dev-nb-api-frc-nsg"
vnet_name                    = "dev-nb-api-frc-vnet"
vnet_address_space           = "10.250.250.0/24"
pe_subnet_name               = "subnet-pe"
pe_subnet_address_space      = "10.250.250.0/26"
app_subnet_name              = "subnet-app"
app_subnet_address_space     = "10.250.250.64/26"
key_vault_name               = "dev-nb-api-frc-kv"
app_service_plan_name        = "dev-nb-api-frc-asp"
app_service_name             = "dev-nb-api-frc-app"
app_service_container_image  = "novabank-api:v1.0.0"
app_service_plan_sku_name    = "S1"
container_registry_name      = "devnbapifrcacr"
container_registry_sku       = "Premium"
postgres_server_name         = "dev-nb-api-frc-psql"
postgres_server_sku          = "B_Standard_B1ms"
postgres_admin_login         = "psqladmin"
postgres_database_name       = "dev-nb-api-frc-db"

#d-nb-api-frc