environment                  = "dev"
subscription_id              = "8486ac29-bcbd-4691-9ff6-52a901335eb0"
location                     = "francecentral"
resource_group_name          = "cs-api-dev-frc-rg"
identity_name                = "cs-api-dev-frc-id"
log_analytics_workspace_name = "cs-api-dev-frc-laws"
application_insights_name    = "cs-api-dev-frc-ai"
nsg_name                     = "cs-api-dev-frc-nsg"
vnet_name                    = "cs-api-dev-frc-vnet"
vnet_address_space           = "10.250.250.0/24"
pe_subnet_name               = "subnet-pe"
pe_subnet_address_space      = "10.250.250.0/26"
app_subnet_name              = "subnet-app"
app_subnet_address_space     = "10.250.250.64/26"
key_vault_name               = "cs-api-dev-frc-kv"
app_service_plan_name        = "cs-api-dev-frc-asp"
app_service_name             = "cs-api-dev-frc-app"
app_service_container_image  = "contoso-api:v2.0.0"
app_service_plan_sku_name    = "S1"
container_registry_name      = "csapidevfrcacr"
container_registry_sku       = "Premium"
postgres_server_name         = "cs-api-dev-frc-psql"
postgres_server_sku          = "B_Standard_B1ms"
postgres_admin_login         = "psqladmin"
postgres_database_name       = "cs-api-dev-frc-db"

#d-cs-api-frc
