environment                  = "prod"
subscription_id              = "8486ac29-bcbd-4691-9ff6-52a901335eb0"
location                     = "swedencentral"
resource_group_name          = "prod-nb-api-swc-rg"
identity_name                = "prod-nb-api-swc-id"
log_analytics_workspace_name = "prod-nb-api-swc-laws"
application_insights_name    = "prod-nb-api-swc-ai"
nsg_name                     = "prod-nb-api-swc-nsg"
vnet_name                    = "prod-nb-api-swc-vnet"
vnet_address_space           = "10.250.100.0/24"
pe_subnet_name               = "subnet-pe"
pe_subnet_address_space      = "10.250.100.0/26"
app_subnet_name              = "subnet-app"
app_subnet_address_space     = "10.250.100.64/26"
key_vault_name               = "prod-nb-api-swc-kv"
app_service_plan_name        = "prod-nb-api-swc-asp"
app_service_name             = "prod-nb-api-swc-app"
app_service_container_image  = "novabank-api:v1.0.0"
app_service_plan_sku_name    = "P1V4"
container_registry_name      = "prodnbapiswcacr"
container_registry_sku       = "Premium"
postgres_server_name         = "prod-nb-api-swc-psql"
postgres_server_sku          = "GP_Standard_D2s_v3"
postgres_admin_login         = "psqladmin"
postgres_database_name       = "prod-nb-api-swc-db"

#prod-nb-api-swc