environment                  = "dev"
subscription_id              = "8486ac29-bcbd-4691-9ff6-52a901335eb0"
location                     = "swedencentral"
resource_group_name          = "d-nb-api-swc-rg"
identity_name                = "d-nb-api-swc-id"
log_analytics_workspace_name = "d-nb-api-swc-laws"
application_insights_name    = "d-nb-api-swc-ai"
nsg_name                     = "d-nb-api-swc-nsg"
vnet_name                    = "d-nb-api-swc-vnet"
vnet_address_space           = "10.250.250.0/24"
pe_subnet_name               = "subnet-pe"
pe_subnet_address_space      = "10.250.250.0/26"
app_subnet_name              = "subnet-app"
app_subnet_address_space     = "10.250.250.64/26"
key_vault_name               = "d-nb-api-swc-kv"
app_service_plan_name        = "d-nb-api-swc-asp"
app_service_name             = "d-nb-api-swc-app"
app_service_container_image  = "novabank-api:v1.0.0"
app_service_plan_sku_name    = "S1"
container_registry_name      = "devnbapiswcacr"
container_registry_sku       = "Premium"
postgres_server_name         = "d-nb-api-swc-psql"
postgres_server_sku          = "B_Standard_B1ms"
postgres_admin_login         = "psqladmin"
postgres_database_name       = "d-nb-api-swc-db"

#d-nb-api-swc