environment                  = "prod"
subscription_id              = "8486ac29-bcbd-4691-9ff6-52a901335eb0"
location                     = "francecentral"
resource_group_name          = "nb-api-prod-frc-rg"
identity_name                = "nb-api-prod-frc-id"
log_analytics_workspace_name = "nb-api-prod-frc-laws"
application_insights_name    = "nb-api-prod-frc-ai"
nsg_name                     = "nb-api-prod-frc-nsg"
vnet_name                    = "nb-api-prod-frc-vnet"
vnet_address_space           = "10.250.100.0/24"
pe_subnet_name               = "subnet-pe"
pe_subnet_address_space      = "10.250.100.0/26"
app_subnet_name              = "subnet-app"
app_subnet_address_space     = "10.250.100.64/26"
key_vault_name               = "nb-api-prod-frc-kv"
app_service_plan_name        = "nb-api-prod-frc-asp"
app_service_name             = "nb-api-prod-frc-app"
app_service_container_image  = "novabank-api:v2.0.0"
app_service_plan_sku_name    = "P0v3"
container_registry_name      = "nbapiprodfrcacr"
container_registry_sku       = "Premium"
postgres_server_name         = "nb-api-prod-frc-psql"
postgres_server_sku          = "GP_Standard_D2s_v3"
postgres_admin_login         = "psqladmin"
postgres_database_name       = "nb-api-prod-frc-db"

#prod-nb-api-frc