environment                  = "dev"
subscription_id              = "8486ac29-bcbd-4691-9ff6-52a901335eb0"
location                     = "westeurope"
resource_group_name          = "prod-nb-api-weu-rg"
identity_name                = "prod-nb-api-weu-id"
log_analytics_workspace_name = "prod-nb-api-weu-laws"
application_insights_name    = "prod-nb-api-weu-ai"
nsg_name                     = "prod-nb-api-weu-nsg"
vnet_name                    = "prod-nb-api-weu-vnet"
vnet_address_space           = "10.250.100.0/24"
pe_subnet_name               = "subnet-pe"
pe_subnet_address_space      = "10.250.100.0/26"
app_subnet_name              = "subnet-app"
app_subnet_address_space     = "10.250.100.64/26"
key_vault_name               = "prod-nb-api-weu-kv"
app_service_plan_name        = "prod-nb-api-weu-asp"
app_service_name             = "prod-nb-api-weu-app"
app_service_container_image  = "novabank-api:v1.0.0"
app_service_plan_sku_name    = "S1"
container_registry_name      = "prodnbapiweuacr"
container_registry_sku       = "Premium"
postgres_server_name         = "prod-nb-api-weu-psql"
postgres_server_sku          = "B_Standard_B1ms"
postgres_admin_login         = "psqladmin"
postgres_database_name       = "prod-nb-api-weu-db"

#prod-nb-api-weu